// Auth actions
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// Employees actions
export const EMPLOYEES_FETCH_START = "EMPLOYEES_FETCH_START";
export const EMPLOYEES_FETCH_SUCCESS = "EMPLOYEES_FETCH_SUCCESS";
export const EMPLOYEES_FETCH_FAIL = "EMPLOYEES_FETCH_FAIL";
// Employee actions
export const EMPLOYEE_SELECT = "EMPLOYEE_SELECT";
export const EMPLOYEE_FETCH_START = "EMPLOYEE_FETCH_START";
export const EMPLOYEE_FETCH_SUCCESS = "EMPLOYEE_FETCH_SUCCESS";
export const EMPLOYEE_FETCH_FAIL = "EMPLOYEE_FETCH_FAIL";
export const EMPLOYEE_ADD_START = "EMPLOYEE_ADD_START";
export const EMPLOYEE_ADD_SUCCESS = "EMPLOYEE_ADD_SUCCESS";
export const EMPLOYEE_ADD_FAIL = "EMPLOYEE_ADD_FAIL";
export const EMPLOYEE_EDIT_START = "EMPLOYEE_EDIT_START";
export const EMPLOYEE_EDIT_SUCCESS = "EMPLOYEE_EDIT_SUCCESS";
export const EMPLOYEE_EDIT_FAIL = "EMPLOYEE_EDIT_FAIL";
export const EMPLOYEE_CANCEL = "EMPLOYEE_CANCEL";
export const EMPLOYEE_DELETE_START = "EMPLOYEE_DELETE_START";
export const EMPLOYEE_DELETE_SUCCESS = "EMPLOYEE_DELETE_SUCCESS";
export const EMPLOYEE_DELETE_FAIL = "EMPLOYEE_DELETE_FAIL";

// Customers
export const CUSTOMERS_FETCH_START = "CUSTOMERS_FETCH_START";
export const CUSTOMERS_FETCH_SUCCESS = "CUSTOMERS_FETCH_SUCCESS";
export const CUSTOMERS_FETCH_FAIL = "CUSTOMERS_FETCH_FAIL";
export const CUSTOMER_SELECTED = "CUSTOMER_SELECTED";
export const CUSTOMER_EDITED = "CUSTOMER_EDITED";

// Projects
export const PROJECTS_FETCH_START = "PROJECTS_FETCH_START";
export const PROJECTS_FETCH_SUCCESS = "PROJECTS_FETCH_SUCCESS";
export const PROJECTS_FETCH_FAIL = "PROJECTS_FETCH_FAIL";
export const PROJECT_SELECTED = "PROJECT_SELECTED";
export const PROJECT_EDITED = "PROJECT_EDITED";

// Calendar
export const LOAD_CALENDAR_MONTH = "LOAD_CALENDAR_MONTH";
export const LOAD_CALENDAR_MONTH_SUCCESS = "LOAD_CALENDAR_MONTH_SUCCESS";
export const LOAD_CALENDAR_MONTH_FAIL = "LOAD_CALENDAR_MONTH_FAIL";
// Task
export const TASK_EDITED_SUCCESS = "TASK_EDITED_SUCCESS";
export const TASK_EDITED_FAIL = "TASK_EDITED_FAIL";
